### ISSUE TITLE
Cargo.toml metadata points to wrong GitHub repo

### ISSUE THREAD

**Issue by dtolnay** [dpc/rust-default#1]
The `homepage` and `repository` are set as https://github.com/dpc/default.

Separately, per [C-METADATA](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-metadata) we don't need a homepage that is redundant with the repository link. It would be better to leave it out.

**Comment by dtolnay** [comment]
Mentioning @dpc since you aren't watching the repo.

**Comment by dpc** [comment]
Thank for pointing it out!

**Comment by dpc** [comment]
Should be fixed now..
